// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/14/2026, 5:42:41 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/Mythic One/f14/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Mythic One/f14/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Mythic One/f14/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Mythic One/f14/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Mythic One/f14/plugins/**/*.{js,ts,mjs}","D:/Mythic One/f14/composables/**/*.{js,ts,mjs}","D:/Mythic One/f14/utils/**/*.{js,ts,mjs}","D:/Mythic One/f14/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Mythic One/f14/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Mythic One/f14/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Mythic One/f14/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;